module TMBGIntrinsicIdealGeometry

using LinearAlgebra

export polar_frame_transport,
       c3_kahler_metric,
       c3_ideal_link_amplitude

"""
Return the unitary polar transport and singular values of an inter-frame
overlap.  The polar transport is covariant under independent unitary gauge
rotations of the frames at the two endpoints.
"""
function polar_frame_transport(overlap::AbstractMatrix{<:Complex})
    factorization = svd(overlap)
    return factorization.U * factorization.Vt, factorization.S
end

"""
The unique Cartesian ideal Kähler metric compatible with C3 symmetry and a
rank-one Berry curvature `curvature`.  It saturates
`Tr(g) = abs(curvature)` pointwise.
"""
function c3_kahler_metric(curvature::Real)
    scale = abs(curvature) / 2
    return [scale 0.0; 0.0 scale]
end

"""
Finite-link modulus generated by the midpoint C3 Kähler metric.  For a small
Cartesian step `delta`, `1 - abs(F)^2` approaches
`delta' * g_ideal * delta`.
"""
function c3_ideal_link_amplitude(
    delta::AbstractVector{<:Real},
    curvature_start::Real,
    curvature_end::Real,
)
    midpoint_scale = (abs(curvature_start) + abs(curvature_end)) / 4
    distance = midpoint_scale * dot(delta, delta)
    return exp(-distance / 2)
end

end
