module TMBGMagneticHW

using LinearAlgebra

include("TMBGHybridWannier.jl")
using .TMBGHybridWannier
using .TMBGHybridWannier.TMBGZeroField
using .TMBGHybridWannier.WangContinuum

export FluxSpec,
       physical_flux,
       MagneticHWModel,
       build_magnetic_hw,
       solve_magnetic_hw,
       magnetic_grid,
       build_trial_matrices,
       finite_box_x_integral,
       shifted_overlap_block,
       shifted_field_block

struct FluxSpec
    p::Int
    q::Int
    signB::Int
    function FluxSpec(p::Int, q::Int, signB::Int=1)
        p > 0 || error("Flux numerator p must be positive; use signB for field direction")
        q > 0 || error("Flux denominator q must be positive")
        gcd(p, q) == 1 || error("p/q must be reduced")
        signB in (-1, 1) || error("signB must be +1 or -1")
        new(p, q, signB)
    end
end

physical_flux(flux::FluxSpec) = flux.signB * flux.p // flux.q

mutable struct MagneticHWModel
    model::AbstractWangModel
    flux::FluxSpec
    nq::Int
    l1::Int
    l2::Int
    nvec::Vector{Int}
    svec::Vector{Int}
    k1::Vector{Float64}
    k2::Vector{Float64}
    r::Vector{Int}
    hw::HybridWannierTMBG
    overlap::Array{ComplexF64,3}
    h0_trial::Array{ComplexF64,3}
    hb_trial::Array{ComplexF64,3}
    kinetic_trial::Array{ComplexF64,3}
    uort::Array{ComplexF64,3}
    kinetic::Array{ComplexF64,3}
    spectrum::Array{Float64,2}
    eigvecs::Array{ComplexF64,3}
    overlap_eigs::Array{Float64,2}
    active_chern::Int
    overlap_hermiticity::Float64
    hamiltonian_hermiticity::Float64
end

function magnetic_grid(
    flux::FluxSpec;
    mesh_factor::Int=1,
    mesh_factor1::Int=mesh_factor,
    mesh_factor2::Int=mesh_factor,
)
    mesh_factor1 > 0 || error("mesh_factor1 must be positive")
    mesh_factor2 > 0 || error("mesh_factor2 must be positive")
    q = flux.q
    # nq controls the k1 index shift generated by magnetic translation and is
    # fixed by l1/(2q).  It is independent of the external k2 sampling.
    nq = mesh_factor1
    l1 = 2 * q * mesh_factor1
    l2 = 2 * mesh_factor2
    k1 = collect(0:(l1 - 1)) ./ l1
    k2 = collect(0:(l2 - 1)) ./ (l2 * q)
    r = collect(0:(q - 1))
    return nq, l1, l2, k1, k2, r
end

@inline full_k2_index(l2::Int, ir::Int, i2::Int) = (ir - 1) * l2 + i2

function precompute_shift_mats(model::AbstractWangModel, gc::Int;
                               periodic::Bool=model.periodic_G)
    shifts = Dict{Tuple{Int,Int},Matrix{ComplexF64}}()
    for dn1 in -gc:gc, dn2 in -gc:gc
        shifts[(dn1, dn2)] = gauge_shift_matrix(model, dn1, dn2; periodic=periodic)
    end
    return shifts
end

function shifted_overlap_block(
    model::AbstractWangModel,
    hw::HybridWannierTMBG,
    shifts::Dict{Tuple{Int,Int},Matrix{ComplexF64}},
    i1r::Int,
    i2r_full::Int,
    i1c::Int,
    i2c_full::Int,
    dg1::Int,
    dg2::Int,
)
    V = get(shifts, (dg1, dg2), nothing)
    nactive = size(hw.WLS, 2)
    V === nothing && return zeros(ComplexF64, nactive, nactive)
    wr = @view hw.WLS[:, :, i1r, i2r_full]
    wc = @view hw.WLS[:, :, i1c, i2c_full]
    return Matrix(wr' * V * wc)
end

function finite_box_x_integral(delta_x::Float64, length_x::Float64)
    abs(delta_x) < 1e-13 && return 0.0 + 0.0im
    z = delta_x * length_x / 2
    numerator = length_x * delta_x * cos(z) - 2sin(z)
    return numerator / (im * length_x * delta_x^2)
end

function shifted_field_block(
    model::AbstractWangModel,
    hw::HybridWannierTMBG,
    i1r::Int,
    i2r_full::Int,
    i1c::Int,
    i2c_full::Int,
    dg2::Int,
    base_delta_x::Float64,
    length_x::Float64,
)
    nactive = size(hw.WLS, 2)
    nlocal = local_dimension(model)
    wr = @view hw.WLS[:, :, i1r, i2r_full]
    wc = @view hw.WLS[:, :, i1c, i2c_full]
    vy = velocity_y(model)
    result = zeros(ComplexF64, nactive, nactive)

    # In the Wang frame g1 is parallel to x. The y integral fixes the second
    # reciprocal index, while x couples every first-index harmonic exactly.
    # Unlike the overlap, x does not impose a delta function on the two Bloch
    # k1 values, so i1r and i1c remain independent.
    abs(model.g1[2]) < 1e-11 || error("Wang g1 must be parallel to x")
    for (ig, grow) in enumerate(model.Glist)
        rr = (nlocal * (ig - 1) + 1):(nlocal * ig)
        wrg = @view wr[rr, :]
        for (jg, gcol) in enumerate(model.Glist)
            gcol[2] - grow[2] == dg2 || continue
            delta_x = base_delta_x +
                      (gcol[1] - grow[1]) * model.g1[1] +
                      dg2 * model.g2[1]
            xelem = finite_box_x_integral(delta_x, length_x)
            abs(xelem) < 1e-15 && continue
            cc = (nlocal * (jg - 1) + 1):(nlocal * jg)
            wcg = @view wc[cc, :]
            result .+= xelem .* (wrg' * vy * wcg)
        end
    end
    return result
end

function build_field_trial(
    model::AbstractWangModel,
    hw::HybridWannierTMBG,
    flux::FluxSpec,
    l1::Int,
    l2::Int,
    k1::Vector{Float64},
    r::Vector{Int},
    nvec::Vector{Int},
    svec::Vector{Int},
)
    p_signed = flux.signB * flux.p
    q = flux.q
    nactive = size(hw.WLS, 2)
    dim_trial = nactive * q * length(nvec)
    hb_trial = zeros(ComplexF64, dim_trial, dim_trial, l1 * l2)
    HB = reshape(hb_trial, nactive, q, length(nvec), nactive, q,
                 length(nvec), l1, l2)
    lB = magnetic_length(model, flux.p, flux.q)
    length_x = l1 * model.a1[1]
    field_prefactor = field_coupling_sign(model, flux.signB) / lB^2
    qphi = (p_signed / q) .* (0.5 .* model.g1 .+ model.g2)

    for s1 in svec
        external_phase = @. exp(1im * 2pi * k1 * s1) *
                            exp(-1im * pi * s1 * (s1 - 1) * p_signed / (2q))
        for i2 in 1:l2, ir_r in 1:q
            # Magnetic-sector relation follows from the y integral. It is
            # retained explicitly here, while k1 on the two sides is free.
            tmp_r = ir_r - s1 * p_signed
            ir_c = mod(tmp_r - 1, q) + 1
            i2r_full = full_k2_index(l2, ir_r, i2)
            i2c_full = full_k2_index(l2, ir_c, i2)
            k2row = (i2 - 1) / (l2 * q) + (ir_r - 1) / q
            k2col = (i2 - 1) / (l2 * q) + (ir_c - 1) / q

            for i1r in 1:l1, i1c in 1:l1
                kred_row = [(i1r - 1) / l1, k2row]
                kred_col = [(i1c - 1) / l1, k2col]
                krow = kred_row[1] .* model.g1 .+ kred_row[2] .* model.g2
                kcol = kred_col[1] .* model.g1 .+ kred_col[2] .* model.g2
                base_delta = kcol .+ s1 .* qphi .- krow
                dg2_float = -base_delta[2] / model.g2[2]
                dg2 = round(Int, dg2_float)
                abs(dg2_float - dg2) < 1e-9 || continue
                block = field_prefactor .* shifted_field_block(
                    model, hw, i1r, i2r_full, i1c, i2c_full,
                    dg2, base_delta[1], length_x,
                ) ./ l1

                for n2i in eachindex(nvec), n1i in eachindex(nvec)
                    internal_phase = exp(1im * 2pi * k1[i1r] * nvec[n1i]) *
                                     exp(-1im * 2pi * k1[i1c] * (s1 + nvec[n2i]))
                    phase = internal_phase .* external_phase
                    HB[:, ir_r, n1i, :, ir_c, n2i, :, i2] .+=
                        reshape(block, nactive, nactive, 1) .*
                        reshape(phase, 1, 1, l1)
                end
            end
        end
    end
    return hb_trial
end

function relative_hermiticity(A::AbstractMatrix{ComplexF64})
    return norm(A - A') / max(norm(A), eps(Float64))
end

function max_relative_hermiticity(A::Array{ComplexF64,3})
    return maximum(relative_hermiticity(@view A[:, :, ik]) for ik in axes(A, 3))
end

function build_trial_matrices(
    model::AbstractWangModel,
    hw::HybridWannierTMBG,
    flux::FluxSpec,
    nq::Int,
    l1::Int,
    l2::Int,
    k1::Vector{Float64},
    r::Vector{Int};
    nvec::Vector{Int}=collect(0:1),
    svec::Vector{Int}=collect(-4:4),
    gc::Int=4,
    reciprocal_shift_periodic::Bool=model.periodic_G,
)
    p_signed = flux.signB * flux.p
    q = flux.q
    nactive = size(hw.WLS, 2)
    dim_trial = nactive * q * length(nvec)
    nk = l1 * l2
    overlap = zeros(ComplexF64, dim_trial, dim_trial, nk)
    h0_trial = zeros(ComplexF64, dim_trial, dim_trial, nk)
    shifts = precompute_shift_mats(model, gc; periodic=reciprocal_shift_periodic)

    O = reshape(overlap, nactive, q, length(nvec), nactive, q, length(nvec), l1, l2)
    H0 = reshape(h0_trial, nactive, q, length(nvec), nactive, q, length(nvec), l1, l2)

    for s1 in svec
        tmp1 = collect(1:l1) .- s1 * p_signed * nq
        k1c = mod.(tmp1 .- 1, l1) .+ 1
        dg1s = div.(tmp1 .- k1c, l1)

        tmp_r = collect(1:q) .- s1 * p_signed
        r2 = mod.(tmp_r .- 1, q) .+ 1
        dg2s = div.(tmp_r .- r2, q)

        external_phase = @. exp(1im * 2pi * k1 * s1) *
                            exp(-1im * pi * s1 * (s1 - 1) * p_signed / (2q))

        for i2 in 1:l2
            for ir_r in 1:q
                ir_c = r2[ir_r]
                dg2 = dg2s[ir_r]
                i2r_full = full_k2_index(l2, ir_r, i2)
                i2c_full = full_k2_index(l2, ir_c, i2)
                for i1r in 1:l1
                    i1c = k1c[i1r]
                    dg1 = dg1s[i1r]
                    (abs(dg1) <= gc && abs(dg2) <= gc) || continue
                    mblock = shifted_overlap_block(model, hw, shifts, i1r, i2r_full,
                                                   i1c, i2c_full, dg1, dg2) ./ l1
                    # Eq. (B.18) of Wang-Vafek: H0 acts on the bra/row before
                    # the magnetic-scattering overlap. No row/column averaging.
                    hrow = @view hw.Hwk[:, :, i1r, i2r_full]
                    h0block = Matrix(hrow * mblock)
                    for n2i in eachindex(nvec), n1i in eachindex(nvec)
                        internal_phase = exp(1im * 2pi * k1[i1r] * nvec[n1i]) *
                                         exp(-1im * 2pi * k1[i1c] * (s1 + nvec[n2i]))
                        phase = internal_phase .* external_phase
                        phase3 = reshape(phase, 1, 1, l1)
                        O[:, ir_r, n1i, :, ir_c, n2i, :, i2] .+=
                            reshape(mblock, nactive, nactive, 1) .* phase3
                        H0[:, ir_r, n1i, :, ir_c, n2i, :, i2] .+=
                            reshape(h0block, nactive, nactive, 1) .* phase3
                    end
                end
            end
        end
    end
    hb_trial = build_field_trial(model, hw, flux, l1, l2, k1, r, nvec, svec)
    return overlap, h0_trial, hb_trial
end

function orthonormalize_and_solve(
    overlap::Array{ComplexF64,3},
    htrial::Array{ComplexF64,3},
    dim_phys::Int;
    norm_tol::Float64=1e-10,
    overlap_hermiticity_tol::Float64=1e-8,
    raw_hamiltonian_tol::Float64=0.08,
)
    dim_trial = size(overlap, 1)
    nk = size(overlap, 3)
    dim_phys <= dim_trial || error("Physical rank exceeds trial-space dimension")
    uort = zeros(ComplexF64, dim_trial, dim_phys, nk)
    kinetic = zeros(ComplexF64, dim_phys, dim_phys, nk)
    spectrum = zeros(Float64, dim_phys, nk)
    eigvecs = zeros(ComplexF64, dim_phys, dim_phys, nk)
    overlap_eigs = zeros(Float64, dim_trial, nk)

    for ik in 1:nk
        O = Matrix(@view overlap[:, :, ik])
        H = Matrix(@view htrial[:, :, ik])
        relative_hermiticity(O) <= overlap_hermiticity_tol ||
            error("Overlap matrix is not Hermitian at k index $ik")
        relative_hermiticity(H) <= raw_hamiltonian_tol ||
            error("Magnetic Hamiltonian truncation is unconverged at k index $ik")
        H = (H + H') / 2

        Fo = eigen(Hermitian(O))
        overlap_eigs[:, ik] .= Fo.values
        keep = (dim_trial - dim_phys + 1):dim_trial
        vals = Fo.values[keep]
        minimum(vals) > norm_tol ||
            error("Retained magnetic trial norm is nonpositive or unconverged at k index $ik")
        U = Fo.vectors[:, keep] * Diagonal(1 ./ sqrt.(vals))
        uort[:, :, ik] .= U
        kinetic[:, :, ik] .= U' * H * U
        relative_hermiticity(@view kinetic[:, :, ik]) <= 10overlap_hermiticity_tol ||
            error("Orthonormal magnetic Hamiltonian is not Hermitian at k index $ik")
        Fh = eigen(Hermitian(@view kinetic[:, :, ik]))
        spectrum[:, ik] .= Fh.values
        eigvecs[:, :, ik] .= Fh.vectors
    end
    return uort, kinetic, spectrum, eigvecs, overlap_eigs
end

function build_magnetic_hw(
    model::AbstractWangModel,
    flux::FluxSpec=FluxSpec(1, 20, 1);
    mesh_factor::Int=1,
    mesh_factor1::Int=mesh_factor,
    mesh_factor2::Int=mesh_factor,
    nactive::Int=4,
    nvec::Vector{Int}=collect(0:1),
    svec::Vector{Int}=collect(-4:4),
    gc::Int=4,
    active_chern::Union{Nothing,Int}=nothing,
    raw_hamiltonian_tol::Float64=0.08,
)
    nq, l1, l2, k1, k2, r = magnetic_grid(
        flux;
        mesh_factor=mesh_factor,
        mesh_factor1=mesh_factor1,
        mesh_factor2=mesh_factor2,
    )
    # The unfolded zero-field k2 grid contains q folded sectors for each
    # external magnetic-BZ k2 point.  This equals l1 only on isotropic meshes.
    hw = build_hybrid_wannier(model, l1, l2 * flux.q; nactive=nactive)
    overlap, h0_trial, hb_trial = build_trial_matrices(
        model, hw, flux, nq, l1, l2, k1, r;
        nvec=nvec, svec=svec, gc=gc,
    )
    htrial = h0_trial + hb_trial
    overlap_hermiticity = max_relative_hermiticity(overlap)
    hamiltonian_hermiticity = max_relative_hermiticity(htrial)
    resolved_chern = isnothing(active_chern) ? hw.chern : active_chern
    dim_phys = nactive * flux.q + flux.signB * resolved_chern * flux.p
    uort, kinetic, spectrum, eigvecs, overlap_eigs = orthonormalize_and_solve(
        overlap, htrial, dim_phys; raw_hamiltonian_tol=raw_hamiltonian_tol,
    )
    return MagneticHWModel(model, flux, nq, l1, l2, nvec, svec, k1, k2, r,
                           hw, overlap, h0_trial, hb_trial, htrial, uort,
                           kinetic, spectrum, eigvecs, overlap_eigs,
                           resolved_chern, overlap_hermiticity,
                           hamiltonian_hermiticity)
end

function build_magnetic_hw(
    model::TMBGModel;
    p::Int=1,
    q::Int=20,
    signB::Int=1,
    lg::Int=max(7, 2model.params.N + 1),
    periodic_G::Bool=true,
    kwargs...,
)
    wang_model = build_tmbg_wang(model.params; lg=lg, periodic_G=periodic_G)
    return build_magnetic_hw(wang_model, FluxSpec(p, q, signB); kwargs...)
end

solve_magnetic_hw(args...; kwargs...) = build_magnetic_hw(args...; kwargs...)

end
